### ISSUE TITLE
Test in-line function performance

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#105]
A follow-up to #7 , we need to make a table with 100, and then maybe 1000, rows that include on on-click function with each row. We need to make sure that performance WITH [on-click] lambda per-entry functions is not dramatically worse than performance without.

**Comment by dalpal07** [comment]
Test 1:
- Paging on
- Sort fn's (in-line lambdas)
- Slowed down substantially at 1,000,000 entries
Test 2:
- Paging off
- No Sort fn's
- Broke at 100,000
Test 3:
- Paging off
- Sort fn's
- Broke at 100,000

Looks like paging helps prevent the table from breaking with larger loads, but it still slows down with REALLY BIG data sets. Without paging, the table breaks with 100,000 entries. I didn't notice a significant difference in slowing down when sort fn's were present (with inline lambdas, applying to each entry in the data set) as opposed to when they were not.
