### ISSUE TITLE
Refactor out valfn

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#107]
Consider removing valfn completely so that no function receives the arg from valfn, but instead everything just receives the whole entry. What would be the costs of this?

**Comment by dalpal07** [comment]
@WorldsEndless I don't think it's worth taking away the valfn option. valfn is powerful because it is a single key that can be used for filtering, sorting, and displaying if desired. Plus, it would break all of our applications if we refactored it out.
