### ISSUE TITLE
Version bump to 19

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#120]
I made a hotfix to v. 18.9 because the fields losing focus was breaking usability. However, changelog still needs to be updated before fully going to v19.

**Comment by dalpal07** [comment]
- Code clean up (added internal file, fixed inline lambdas, implemented keys, and added unique key to handle duplicate columns and/or rows)
- Added codox documentation files
- Refactored paging so that it always happens after filtering and sorting
