### ISSUE TITLE
Filters should be case insensitive

### ISSUE THREAD

**Issue by CambodianCoder** [BYU-ODH/retabled#3]
Filtering by a column should be case-insensitive. For example, if the column displays names, and the name "Mark" is in that column, typing in "Mark" or "mark" into the filter input would return the same results.

**Comment by WorldsEndless** [comment]
Make this toggle-able: ignore-case? should be an optional specification that defaults to true (which is the case you have successfully here), but it should be an option to enable case sensitivity if desired.
