### ISSUE TITLE
Multiple filters applied simultaneously

### ISSUE THREAD

**Issue by CambodianCoder** [BYU-ODH/retabled#4]
A possible enhancement would be to allow multiple filters to be applied simultaneously. The current operation only allows one filter at a time. For example, if two columns are shown on the table, such as name and email, typing into the name filter filters all the rows by name. However, if one then types into the email filter, without removing the text from the name filter, the rows that are shown are only filtered based on the most recently applied filter, that of email, even though the name filter still has text in it.

**Comment by CambodianCoder** [comment]
Also, having text in the first filter that matches a certain row, and then adding text to a new filter that doesn't match any rows causes all results to be shown again, even though only a few rows might have matched the first filter, which still has text in it.

**Comment by dalpal07** [comment]
It looks like this issue is not an issue anymore.
