### ISSUE TITLE
Make any row stickiable

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#46]
as an extension of #39 , now make any row potentially sticky

**Comment by dalpal07** [comment]
I'm not sure if it's possible to make rows/columns stickiable without hard coding in values for their position. It may not be worth adding this functionality.

**Comment by WorldsEndless** [comment]
would need a setting map that either specifies the dimensions of cells, or uses javascript to dynamically retrieve the dimensions.
