### ISSUE TITLE
Version bump to 15

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#54]
Once all the PRs are through, make a new version bump, which will include changelog info for what has been done this version.

**Comment by dalpal07** [comment]
Recent changes made:
- Filtered/Sorted columns are highlighed in gray
- Filtering appears in and can be accomplished from URL (optional)
- Tables can have a scroll bar across X and Y axis (optional)
- First and last columns can be made sticky (optional)
- "Go to..." box for paging
- Headers have a sticky border on the bottom
- Paging controls no longer have a border on the bottom
- Paging controls are sticky to the top left

**Comment by dalpal07** [comment]
@mbisel is there anything else that you can think of for recent changes that ought to be mentioned?

**Comment by mbisel** [comment]
- table-ids can be set, otherwise they will be generated
- :click-to-filter was added as an option for filter
