### ISSUE TITLE
add warnings/checks for URL length

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#66]
Concerning length of URL, we should protect against breaking with more than 2000 chars.

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

Probably we should ALWAYS emit warnings

options: 
- Start ignoring further text at some point
- Enforce char limits on the filter inputs

**Comment by WorldsEndless** [comment]
note that a malicious actor could craft a link that would use unprotected url lengths somehow

**Comment by dalpal07** [comment]
@WorldsEndless I tried to break the program by entering in 344,001 chars directly into the URL as well as into one input field. Though slow to process, nothing broke and the program performed as expected. I think that this issue may be a non-issue.
