### ISSUE TITLE
"go to" should clear when new entry option is selected

### ISSUE THREAD

**Issue by dalpal07** [BYU-ODH/retabled#88]
When a new entry option is selected, the page automatically resets back to the first. The "go to" box should clear out at this point as well.

**Comment by WorldsEndless** [comment]
For when new page number-of-entries changes, resetting the view appropriately

**Comment by WorldsEndless** [comment]
when you click on the goto area it empties so you can type the page you want.

However, when you click OFF it (eg I changed my mind), it should restore the page I'm on
