### ISSUE TITLE
make filter-val-fn

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/retabled#89]
Some apps use many rows to affect their display, which is what the valfn is used for, but there should be an optional filter-val-fn that is what is considered (if present) when filtering by a value on this row

**Comment by dalpal07** [comment]
@WorldsEndless Is this supposed to be like the optional sortfn that we have in place?

**Comment by WorldsEndless** [comment]
The problem is that the filter works upon the entire row, for example, when `:valfn identity`, and so when they filter, it may be really unclear why they are seeing the results that they do because it may have nothing apparent  matching. Sometimes this is good, but sometimes it is very unexpected. The sortfn should receive automatically as its arg the whole row/entry, just like valfn does.
